[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "platformio"
dynamic = ["version", "dependencies"]
description = "Your Gateway to Embedded Software Development Excellence. Unlock the true potential of embedded software development with PlatformIO's collaborative ecosystem, embracing declarative principles, test-driven methodologies, and modern toolchains for unrivaled success."
readme = "README.rst"
authors = [
    {name = "PlatformIO Labs", email = "contact@piolabs.com"}
]
license = {text = "Apache Software License"}
requires-python = ">=3.6"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Compilers",
]
keywords = [
    "iot", "embedded", "arduino", "mbed", "esp8266", "esp32", "fpga",
    "firmware", "continuous-integration", "cloud-ide", "avr", "arm",
    "ide", "unit-testing", "hardware", "verilog", "microcontroller", "debug"
]

[project.urls]
Homepage = "https://platformio.org"

[project.scripts]
platformio = "platformio.__main__:main"
pio = "platformio.__main__:main"
piodebuggdb = "platformio.__main__:debug_gdb_main"

[tool.setuptools.packages.find]
include = ["platformio", "platformio.*"]

[tool.setuptools.package-data]
platformio = [
    "assets/system/99-platformio-udev.rules",
    "project/integration/tpls/*/*.tpl",
    "project/integration/tpls/*/.*.tpl",
    "project/integration/tpls/*/.*/*.tpl",
    "project/integration/tpls/*/*/*.tpl",
    "project/integration/tpls/*/*/*/*.tpl",
]

[tool.setuptools.dynamic]
version = {attr = "platformio.__version__"}
